export const infs: any [] = [
    
{name:"Author",para:"Certainly listening no behaviour existence assurance situation",imagess:"./assets/images/brand/jpg/image-33.png",calenderimg:"./assets/images/brand/svg/calendar_month_20dp_FILL0_wght400_GRAD0_opsz20.svg",dates:"jul/15/2018",commentimg:"./assets/images/brand/svg/forum_20dp_FILL0_wght400_GRAD0_opsz20.svg",commentnum:"01",eyeimg:"./assets/images/brand/svg/visibility_20dp_FILL0_wght400_GRAD0_opsz20.svg",eyenum:"301"},
{name:"Author",para:"Certainly listening no behaviour existence assurance situation",imagess:"./assets/images/brand/jpg/img-32.png",calenderimg:"./assets/images/brand/svg/calendar_month_20dp_FILL0_wght400_GRAD0_opsz20.svg",dates:"jul/15/2018",commentimg:"./assets/images/brand/svg/forum_20dp_FILL0_wght400_GRAD0_opsz20.svg",commentnum:"01",eyeimg:"./assets/images/brand/svg/visibility_20dp_FILL0_wght400_GRAD0_opsz20.svg",eyenum:"301"},
{name:"Author",para:"Certainly listening no behaviour existence assurance situation",imagess:"./assets/images/brand/jpg/img-34.png",calenderimg:"./assets/images/brand/svg/calendar_month_20dp_FILL0_wght400_GRAD0_opsz20.svg",dates:"jul/15/2018",commentimg:"./assets/images/brand/svg/forum_20dp_FILL0_wght400_GRAD0_opsz20.svg",commentnum:"01",eyeimg:"./assets/images/brand/svg/visibility_20dp_FILL0_wght400_GRAD0_opsz20.svg",eyenum:"301"},
{name:"Author",para:"Certainly listening no behaviour existence assurance situation",imagess:"./assets/images/brand/jpg/img-55.png",calenderimg:"./assets/images/brand/svg/calendar_month_20dp_FILL0_wght400_GRAD0_opsz20.svg",dates:"jul/15/2018",commentimg:"./assets/images/brand/svg/forum_20dp_FILL0_wght400_GRAD0_opsz20.svg",commentnum:"01",eyeimg:"./assets/images/brand/svg/visibility_20dp_FILL0_wght400_GRAD0_opsz20.svg",eyenum:"301"},
{name:"Author",para:"Certainly listening no behaviour existence assurance situation",imagess:"./assets/images/brand/jpg/img-77.png",calenderimg:"./assets/images/brand/svg/calendar_month_20dp_FILL0_wght400_GRAD0_opsz20.svg",dates:"jul/15/2018",commentimg:"./assets/images/brand/svg/forum_20dp_FILL0_wght400_GRAD0_opsz20.svg",commentnum:"01",eyeimg:"./assets/images/brand/svg/visibility_20dp_FILL0_wght400_GRAD0_opsz20.svg",eyenum:"301"},
{name:"Author",para:"Certainly listening no behaviour existence assurance situation",imagess:"./assets/images/brand/jpg/img-55.png",calenderimg:"./assets/images/brand/svg/calendar_month_20dp_FILL0_wght400_GRAD0_opsz20.svg",dates:"jul/15/2018",commentimg:"./assets/images/brand/svg/forum_20dp_FILL0_wght400_GRAD0_opsz20.svg",commentnum:"01",eyeimg:"./assets/images/brand/svg/visibility_20dp_FILL0_wght400_GRAD0_opsz20.svg",eyenum:"301"},
{name:"Author",para:"Certainly listening no behaviour existence assurance situation",imagess:"./assets/images/brand/jpg/img-77.png",calenderimg:"./assets/images/brand/svg/calendar_month_20dp_FILL0_wght400_GRAD0_opsz20.svg",dates:"jul/15/2018",commentimg:"./assets/images/brand/svg/forum_20dp_FILL0_wght400_GRAD0_opsz20.svg",commentnum:"01",eyeimg:"./assets/images/brand/svg/visibility_20dp_FILL0_wght400_GRAD0_opsz20.svg",eyenum:"301"}

]